- name: my play to project 3
  hosts: webserver
  become: true
  tasks:
    - name: uupdate repos
      command: apt update
    - name: install docker
      package: name=docker.io state=present
    - name: start docker service
      service: name=docker state=started
    - name: docker image
      command: docker pull yashas/insurance:3
    - name: docker con
      command: docker run -d -p 4567:8081 yashas/insurance:3
